project:
  type: website
  output-dir: docs
  
website:
  title: "Alice Trevail"
  favicon: images/RFB.png
  navbar:
    logo: images/RFB.png
    left:
      - href: index.qmd
        text: Home
      - href: Projects.qmd
        text: Projects
      - href: People.qmd
        text: People
      - href: Data.qmd
        text: Reproducible research
      - href: Publications.qmd
        text: Publications
  page-footer:
    left: 
      - text: "{{< fa brands google-scholar >}}"
        href: https://scholar.google.com/citations?user=mKYlUsUAAAAJ&hl=en
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0002-6459-5213
      - text: "{{< fa brands github >}}"
        href: https://github.com/AliceTrevail
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/alicetrevail.bsky.social
      - icon: envelope-fill
        href: https://biosciences.exeter.ac.uk/staff/profile/index.php?web_id=Alice_Trevail
    right:
      - text: "© 2025 Alice Trevail | All rights reserved"
      
format:
  html:
    theme: 
      - flatly
      - customstyles.scss
    css: styles.css
    toc: true
    mainfont: Roboto
    link-external-newwindow: true

editor: visual




