---
title: "People"
bibliography: publications.bib
csl: apa-cv.csl
suppress-bibliography: true
link-citations: false
citations-hover: false
---

### Current students

##### PhD

::: grid
::: g-col-3
[**Sabiya Sheikh**](https://ecologyconservation.exeter.ac.uk/people/profile/index.php?web_id=Sabiya_Sheikh) **(2024-2028)**
:::

::: g-col-8
Mapping forage fish and seabird interactions on the Isles of Scilly to inform conservation. Co-supervisor, alongside Kristian Metcalfe (UoE) and Richard Sherley (UoE). *PhD, University of Exeter*
:::
:::

::: grid
::: g-col-3
[**Vance Mak**](https://www.exeter.ac.uk/research/esi/people/profile/index.php?web_id=Vance_Mak) **(2023-2027)**
:::

::: g-col-8
Predicting regional vulnerability of threatened seabirds to offshore wind. Co-supervisor, alongside Cat Horswill (ZSL/UCL), Richard Sherley (UoE), Simon Neill (Bangor University), Sion Roberts (The Crown Estate) and Stu Bearhop (UoE). *PhD, University of Exeter*
:::
:::

::: grid
::: g-col-3
[**Debs Allbrook**](https://ecologyconservation.exeter.ac.uk/staff/profile/index.php?web_id=Debs_Allbrook) **(2022-2026)**
:::

::: g-col-8
Ecology and management of offshore-breeding kittiwakes. Co-supervisor, alongside Richard Sherley (UoE), Richard Delahay (RSKBiocensus), John Swaddle (College of William & Mary), Stu Bearhop (UoE) and Robbie McDonald (UoE). *PhD, University of Exeter*
:::
:::

##### Masters

::: grid
::: g-col-3
**Claudia Treasure-Chapman (2025)**
:::

::: g-col-8
Seabird-vectored nutrient enrichment around a UK offshore archipelago. *MSc Marine Vertebrate Ecology and Conservation, University of Exeter*
:::
:::

### Alumni

##### Masters

::: grid
::: g-col-3
**Joshua Coste (2024)**
:::

::: g-col-8
Red-footed booby navigation at-sea. *Master in Biodiversity, Ecology, Evolution, University of La Réunion*

Thesis accepted in Animal Behaviour
:::
:::

::: grid
::: g-col-3
**Kath O'Brien (2024)**
:::

::: g-col-8
Seabird foraging behaviour to inform conservation on the Isles of Scilly. *MSc Marine Vertebrate Ecology and Conservation, University of Exeter*
:::
:::

::: grid
::: g-col-3
**Millie Thatcher (2024)**
:::

::: g-col-8
Seabird foraging behaviour to inform conservation on the Isles of Scilly. *MSc Marine Vertebrate Ecology and Conservation, University of Exeter*
:::
:::

::: grid
::: g-col-3
**Grace Corcoran (2022)**
:::

::: g-col-8
Migratory ecology of red-footed boobies in the Indian Ocean. *MSc Conservation & Biodiversity, University of Exeter*

::: {.callout-tip collapse="true" appearance="minimal"}
##### Published thesis

::: {style="font-size:16px"}

[@votier2023]

:::
:::
:::
:::

::: grid
::: g-col-3
**Sonia Vallocchia (2020)**
:::

::: g-col-8
Foraging ecology of brown boobies in the Indian Ocean. *MRes Wild Animal Biology, Royal Veterinary College & Zoological Society of London*

::: {.callout-tip collapse="true" appearance="minimal"}
##### Published thesis

::: {style="font-size:16px"}
[@trevail2024a]
:::
:::
:::
:::
